[package]
name = "onefmt-rustfmt"
version = "0.1.0"
edition = "2021"
repository = "https://github.com/nahco314/onefmt-rustfmt"

[lib]
crate-type = ["rlib", "cdylib"]

[dependencies]
anyhow = "1.0.87"
rustfmt-nightly = { version = "1.7.1", git = "https://github.com/rust-lang/rustfmt" }

# The profile that 'cargo dist' will build with
[profile.dist]
inherits = "release"
lto = "thin"

[workspace.metadata.dist]
cargo-dist-version = "0.22.1"
ci = "github"
installers = ["shell", "powershell"]
targets = ["aarch64-apple-darwin", "x86_64-apple-darwin", "x86_64-unknown-linux-gnu", "x86_64-unknown-linux-musl", "x86_64-pc-windows-msvc"]
install-path = "CARGO_HOME"
install-updater = false
package-libraries = ["cdylib"]
install-libraries = ["cdylib"]

[package.metadata.rust-analyzer]
# This package uses #[feature(rustc_private)]
rustc_private = true
